import Navigation from '@/components/Navigation';
import Footer from '@/components/Footer';

export default function ReportPage() {
  return (
    <div className="min-h-screen bg-[#161616] text-white">
      <Navigation />

      {/* Main Content */}
      <div className="max-w-7xl mx-auto px-6 py-16">
        {/* Title Section */}
        <div className="mb-12">
          <div className="inline-block px-4 py-2 bg-primary/20 border border-primary/30 rounded-full text-primary text-sm font-medium mb-4">
            📊 Modernization Complete
          </div>
          <h1 className="text-5xl md:text-6xl font-bold mb-4">
            Modernization Report
          </h1>
          <p className="text-xl text-gray-400">
            Generated by IBM Bob IDE - SpringBoard Hackathon 2026
          </p>
          <p className="text-sm text-gray-500 mt-2">
            Report Date: May 2026
          </p>
        </div>

        {/* Summary Stats */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-12">
          <div className="bg-[#1a1a1a] border border-gray-800 rounded-2xl p-6 hover:border-primary/50 transition-all">
            <div className="text-4xl font-bold text-primary mb-2">9</div>
            <div className="text-sm text-gray-400">Files Refactored</div>
            <div className="mt-3 text-xs text-gray-500">
              Java, XML, Properties, Docker
            </div>
          </div>

          <div className="bg-[#1a1a1a] border border-gray-800 rounded-2xl p-6 hover:border-primary/50 transition-all">
            <div className="text-4xl font-bold text-green-400 mb-2">12</div>
            <div className="text-sm text-gray-400">Issues Fixed</div>
            <div className="mt-3 text-xs text-gray-500">
              Deprecated APIs, Dependencies
            </div>
          </div>

          <div className="bg-[#1a1a1a] border border-gray-800 rounded-2xl p-6 hover:border-primary/50 transition-all">
            <div className="text-4xl font-bold text-blue-400 mb-2">6</div>
            <div className="text-sm text-gray-400">Tests Generated</div>
            <div className="mt-3 text-xs text-gray-500">
              JUnit 5, Mockito, Integration
            </div>
          </div>

          <div className="bg-[#1a1a1a] border border-gray-800 rounded-2xl p-6 hover:border-primary/50 transition-all">
            <div className="text-2xl font-bold text-white mb-2">2.7 → 3.1.5</div>
            <div className="text-sm text-gray-400">Spring Boot</div>
            <div className="mt-3 text-xs text-gray-500">
              Major version upgrade
            </div>
          </div>
        </div>

        {/* Before vs After Comparison */}
        <div className="mb-12">
          <h2 className="text-3xl font-bold mb-6">Before vs After Comparison</h2>
          <div className="bg-[#1a1a1a] border border-gray-800 rounded-2xl overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead className="bg-[#0d1117] border-b border-gray-800">
                  <tr>
                    <th className="text-left px-6 py-4 text-gray-400 font-semibold">Category</th>
                    <th className="text-left px-6 py-4 text-gray-400 font-semibold">Before</th>
                    <th className="text-left px-6 py-4 text-gray-400 font-semibold">After</th>
                  </tr>
                </thead>
                <tbody className="text-gray-300">
                  <tr className="border-b border-gray-800 hover:bg-[#1f1f1f] transition-colors">
                    <td className="px-6 py-4 font-medium">Spring Boot Version</td>
                    <td className="px-6 py-4">
                      <span className="px-3 py-1 bg-red-500/20 text-red-400 rounded-full text-sm">2.7.x</span>
                    </td>
                    <td className="px-6 py-4">
                      <span className="px-3 py-1 bg-green-500/20 text-green-400 rounded-full text-sm">3.1.5</span>
                    </td>
                  </tr>
                  <tr className="border-b border-gray-800 hover:bg-[#1f1f1f] transition-colors">
                    <td className="px-6 py-4 font-medium">Java Version</td>
                    <td className="px-6 py-4">
                      <span className="px-3 py-1 bg-red-500/20 text-red-400 rounded-full text-sm">11</span>
                    </td>
                    <td className="px-6 py-4">
                      <span className="px-3 py-1 bg-green-500/20 text-green-400 rounded-full text-sm">17</span>
                    </td>
                  </tr>
                  <tr className="border-b border-gray-800 hover:bg-[#1f1f1f] transition-colors">
                    <td className="px-6 py-4 font-medium">Docker Base Image</td>
                    <td className="px-6 py-4">
                      <code className="text-sm text-gray-400">openjdk:11</code>
                    </td>
                    <td className="px-6 py-4">
                      <code className="text-sm text-primary">eclipse-temurin:17-jdk-alpine</code>
                    </td>
                  </tr>
                  <tr className="border-b border-gray-800 hover:bg-[#1f1f1f] transition-colors">
                    <td className="px-6 py-4 font-medium">Jakarta Migration</td>
                    <td className="px-6 py-4">
                      <code className="text-sm text-gray-400">javax.*</code>
                    </td>
                    <td className="px-6 py-4">
                      <code className="text-sm text-primary">jakarta.*</code>
                    </td>
                  </tr>
                  <tr className="border-b border-gray-800 hover:bg-[#1f1f1f] transition-colors">
                    <td className="px-6 py-4 font-medium">Test Framework</td>
                    <td className="px-6 py-4">
                      <span className="text-sm text-gray-400">JUnit 4</span>
                    </td>
                    <td className="px-6 py-4">
                      <span className="text-sm text-primary">JUnit 5</span>
                    </td>
                  </tr>
                  <tr className="hover:bg-[#1f1f1f] transition-colors">
                    <td className="px-6 py-4 font-medium">Dependency Injection</td>
                    <td className="px-6 py-4">
                      <span className="text-sm text-gray-400">Old patterns</span>
                    </td>
                    <td className="px-6 py-4">
                      <span className="text-sm text-primary">Spring Boot 3 patterns</span>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>

        {/* Files Changed Section */}
        <div className="mb-12">
          <h2 className="text-3xl font-bold mb-6">Files Changed</h2>
          <div className="space-y-3">
            {/* pom.xml */}
            <div className="bg-[#1a1a1a] border border-gray-800 rounded-xl p-5 hover:border-primary/50 transition-all">
              <div className="flex items-center justify-between">
                <div className="flex-1">
                  <div className="flex items-center space-x-3 mb-2">
                    <code className="text-primary font-mono text-sm">pom.xml</code>
                    <span className="px-2 py-1 bg-red-500/20 text-red-400 rounded text-xs font-medium">High Risk</span>
                  </div>
                  <p className="text-sm text-gray-400">Spring Boot and Java version upgrade</p>
                </div>
                <div className="text-green-500 text-xl">✓</div>
              </div>
            </div>

            {/* SampleActuatorApplication.java */}
            <div className="bg-[#1a1a1a] border border-gray-800 rounded-xl p-5 hover:border-primary/50 transition-all">
              <div className="flex items-center justify-between">
                <div className="flex-1">
                  <div className="flex items-center space-x-3 mb-2">
                    <code className="text-primary font-mono text-sm">SampleActuatorApplication.java</code>
                    <span className="px-2 py-1 bg-green-500/20 text-green-400 rounded text-xs font-medium">Low Risk</span>
                  </div>
                  <p className="text-sm text-gray-400">Updated annotations and added Javadoc</p>
                </div>
                <div className="text-green-500 text-xl">✓</div>
              </div>
            </div>

            {/* SampleController.java */}
            <div className="bg-[#1a1a1a] border border-gray-800 rounded-xl p-5 hover:border-primary/50 transition-all">
              <div className="flex items-center justify-between">
                <div className="flex-1">
                  <div className="flex items-center space-x-3 mb-2">
                    <code className="text-primary font-mono text-sm">SampleController.java</code>
                    <span className="px-2 py-1 bg-yellow-500/20 text-yellow-400 rounded text-xs font-medium">Medium Risk</span>
                  </div>
                  <p className="text-sm text-gray-400">Fixed deprecated patterns and jakarta migration</p>
                </div>
                <div className="text-green-500 text-xl">✓</div>
              </div>
            </div>

            {/* HelloWorldService.java */}
            <div className="bg-[#1a1a1a] border border-gray-800 rounded-xl p-5 hover:border-primary/50 transition-all">
              <div className="flex items-center justify-between">
                <div className="flex-1">
                  <div className="flex items-center space-x-3 mb-2">
                    <code className="text-primary font-mono text-sm">HelloWorldService.java</code>
                    <span className="px-2 py-1 bg-green-500/20 text-green-400 rounded text-xs font-medium">Low Risk</span>
                  </div>
                  <p className="text-sm text-gray-400">Added comprehensive Javadoc documentation</p>
                </div>
                <div className="text-green-500 text-xl">✓</div>
              </div>
            </div>

            {/* ExampleHealthIndicator.java */}
            <div className="bg-[#1a1a1a] border border-gray-800 rounded-xl p-5 hover:border-primary/50 transition-all">
              <div className="flex items-center justify-between">
                <div className="flex-1">
                  <div className="flex items-center space-x-3 mb-2">
                    <code className="text-primary font-mono text-sm">ExampleHealthIndicator.java</code>
                    <span className="px-2 py-1 bg-yellow-500/20 text-yellow-400 rounded text-xs font-medium">Medium Risk</span>
                  </div>
                  <p className="text-sm text-gray-400">Jakarta migration and Javadoc updates</p>
                </div>
                <div className="text-green-500 text-xl">✓</div>
              </div>
            </div>

            {/* ExampleInfoContributor.java */}
            <div className="bg-[#1a1a1a] border border-gray-800 rounded-xl p-5 hover:border-primary/50 transition-all">
              <div className="flex items-center justify-between">
                <div className="flex-1">
                  <div className="flex items-center space-x-3 mb-2">
                    <code className="text-primary font-mono text-sm">ExampleInfoContributor.java</code>
                    <span className="px-2 py-1 bg-yellow-500/20 text-yellow-400 rounded text-xs font-medium">Medium Risk</span>
                  </div>
                  <p className="text-sm text-gray-400">Jakarta migration and documentation</p>
                </div>
                <div className="text-green-500 text-xl">✓</div>
              </div>
            </div>

            {/* ServiceProperties.java */}
            <div className="bg-[#1a1a1a] border border-gray-800 rounded-xl p-5 hover:border-primary/50 transition-all">
              <div className="flex items-center justify-between">
                <div className="flex-1">
                  <div className="flex items-center space-x-3 mb-2">
                    <code className="text-primary font-mono text-sm">ServiceProperties.java</code>
                    <span className="px-2 py-1 bg-green-500/20 text-green-400 rounded text-xs font-medium">Low Risk</span>
                  </div>
                  <p className="text-sm text-gray-400">Updated config binding and added Javadoc</p>
                </div>
                <div className="text-green-500 text-xl">✓</div>
              </div>
            </div>

            {/* application.properties */}
            <div className="bg-[#1a1a1a] border border-gray-800 rounded-xl p-5 hover:border-primary/50 transition-all">
              <div className="flex items-center justify-between">
                <div className="flex-1">
                  <div className="flex items-center space-x-3 mb-2">
                    <code className="text-primary font-mono text-sm">application.properties</code>
                    <span className="px-2 py-1 bg-green-500/20 text-green-400 rounded text-xs font-medium">Low Risk</span>
                  </div>
                  <p className="text-sm text-gray-400">Spring Boot 3 properties and configuration updates</p>
                </div>
                <div className="text-green-500 text-xl">✓</div>
              </div>
            </div>

            {/* Dockerfile */}
            <div className="bg-[#1a1a1a] border border-gray-800 rounded-xl p-5 hover:border-primary/50 transition-all">
              <div className="flex items-center justify-between">
                <div className="flex-1">
                  <div className="flex items-center space-x-3 mb-2">
                    <code className="text-primary font-mono text-sm">Dockerfile</code>
                    <span className="px-2 py-1 bg-yellow-500/20 text-yellow-400 rounded text-xs font-medium">Medium Risk</span>
                  </div>
                  <p className="text-sm text-gray-400">Java 17 base image and security improvements</p>
                </div>
                <div className="text-green-500 text-xl">✓</div>
              </div>
            </div>
          </div>
        </div>

        {/* Bob Sessions Section */}
        <div className="mb-12">
          <h2 className="text-3xl font-bold mb-4">IBM Bob Task Sessions</h2>
          <p className="text-gray-400 mb-6">
            These are the actual Bob IDE sessions used to complete this modernization
          </p>
          
          <div className="grid md:grid-cols-3 gap-6">
            {/* Dev 1 - Analysis */}
            <div className="bg-gradient-to-br from-primary/10 to-transparent border border-primary/30 rounded-2xl p-6">
              <div className="flex items-center space-x-3 mb-4">
                <div className="w-12 h-12 bg-primary/20 rounded-xl flex items-center justify-center">
                  <span className="text-2xl">🔍</span>
                </div>
                <div>
                  <h3 className="font-bold text-lg">Dev 1: Analysis</h3>
                  <p className="text-xs text-gray-400">bob_sessions/dev-1/</p>
                </div>
              </div>
              <div className="space-y-2 text-sm">
                <div className="flex items-center space-x-2">
                  <span className="text-primary">•</span>
                  <span className="text-gray-300">Role: Senior Architect</span>
                </div>
                <div className="flex items-center space-x-2">
                  <span className="text-primary">•</span>
                  <span className="text-gray-300">Mode: Code Analysis</span>
                </div>
                <div className="flex items-center space-x-2">
                  <span className="text-primary">•</span>
                  <span className="text-gray-300">Tasks: Codebase scan, dependency analysis</span>
                </div>
              </div>
            </div>

            {/* Dev 2 - Refactoring */}
            <div className="bg-gradient-to-br from-green-500/10 to-transparent border border-green-500/30 rounded-2xl p-6">
              <div className="flex items-center space-x-3 mb-4">
                <div className="w-12 h-12 bg-green-500/20 rounded-xl flex items-center justify-center">
                  <span className="text-2xl">⚙️</span>
                </div>
                <div>
                  <h3 className="font-bold text-lg">Dev 2: Refactoring</h3>
                  <p className="text-xs text-gray-400">bob_sessions/dev-2/</p>
                </div>
              </div>
              <div className="space-y-2 text-sm">
                <div className="flex items-center space-x-2">
                  <span className="text-green-400">•</span>
                  <span className="text-gray-300">Role: Lead Developer</span>
                </div>
                <div className="flex items-center space-x-2">
                  <span className="text-green-400">•</span>
                  <span className="text-gray-300">Mode: Code Refactoring</span>
                </div>
                <div className="flex items-center space-x-2">
                  <span className="text-green-400">•</span>
                  <span className="text-gray-300">Tasks: Code migration, pattern updates</span>
                </div>
              </div>
            </div>

            {/* Dev 3 - Testing */}
            <div className="bg-gradient-to-br from-blue-500/10 to-transparent border border-blue-500/30 rounded-2xl p-6">
              <div className="flex items-center space-x-3 mb-4">
                <div className="w-12 h-12 bg-blue-500/20 rounded-xl flex items-center justify-center">
                  <span className="text-2xl">✅</span>
                </div>
                <div>
                  <h3 className="font-bold text-lg">Dev 3: Testing</h3>
                  <p className="text-xs text-gray-400">bob_sessions/dev-3/</p>
                </div>
              </div>
              <div className="space-y-2 text-sm">
                <div className="flex items-center space-x-2">
                  <span className="text-blue-400">•</span>
                  <span className="text-gray-300">Role: QA Engineer</span>
                </div>
                <div className="flex items-center space-x-2">
                  <span className="text-blue-400">•</span>
                  <span className="text-gray-300">Mode: Test Generation</span>
                </div>
                <div className="flex items-center space-x-2">
                  <span className="text-blue-400">•</span>
                  <span className="text-gray-300">Tasks: Unit tests, integration tests</span>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* GitHub CTA */}
        <div className="text-center">
          <a 
            href="https://github.com/IBM-Bob-Au-Team/SpringBoard" 
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center space-x-3 px-8 py-4 bg-primary hover:bg-primary/90 text-white font-semibold rounded-lg transition-all transform hover:scale-105 shadow-lg shadow-primary/25"
          >
            <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 24 24">
              <path fillRule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clipRule="evenodd" />
            </svg>
            <span>View Full Code on GitHub</span>
          </a>
          <p className="text-sm text-gray-500 mt-4">
            IBM-Bob-Au-Team/SpringBoard
          </p>
        </div>
      </div>

      <Footer />
    </div>
  );
}

// Made with Bob
